language: bash

before_script:
  - sudo apt-get install rpm
  - rpmbuild --version
  - svn --version --quiet
  - cmake --version

script:
  - bash check_dependencies.sh
  - bash build_model_rpm.sh -h
