language: python
python:
  - "2.7"

install: 
  - sudo apt-get install -qq rpm gfortran
  - bash .travis/install_packagebuilder.sh
  - bash .travis/install_rpmdevtools.sh
  - export PATH=$PATH:$PWD/rpmdevtools-6.8/

before_script:
  - sudo mkdir -p /etc/rpm
  - sudo cp .travis/macros.cmake /etc/rpm
  - export FC=$(which gfortran)

script:
   - build_rpm 2dflowvel --local $PWD
   - build_rpm adi-2d --local $PWD
   - build_rpm aquatellus --local $PWD
   - build_rpm cem --local $PWD
   - build_rpm child --local $PWD
   - build_rpm flex1d --local $PWD
   - build_rpm flex2d --local $PWD
   - build_rpm flex2d-adi --local $PWD
   - build_rpm hydrotrend --local $PWD
   - build_rpm marssim --local $PWD
   - build_rpm sedflux --local $PWD
   - build_rpm storm --local $PWD
