language: python
python:
  - "2.7"

install: 
  - sudo apt-get install -qq rpm
  - wget https://fedorahosted.org/releases/r/p/rpmdevtools/rpmdevtools-6.8.tar.bz2
  - tar -jxf rpmdevtools-6.8.tar.bz2
  - export PATH=$PATH:$PWD/rpmdevtools-6.8/

before_script:
  - rpmbuild --version
  - sudo mkdir -p /etc/rpm
  - sudo cp config/macros.cmake /etc/rpm

script:
  - python check_dependencies.py --help               # check help flag
  - python check_dependencies.py                      # check default
  - python check_dependencies.py --model "hydrotrend" # check model flag
  - python build_model_rpm.py --model hydrotrend
