language: bash

install: 
  - sudo apt-get install -qq rpm
  - wget https://fedorahosted.org/releases/r/p/rpmdevtools/rpmdevtools-6.8.tar.bz2
  - tar -jxf rpmdevtools-6.8.tar.bz2
  - export PATH=$PATH:$PWD/rpmdevtools-6.8/

before_script:
  - rpmbuild --version
  - sudo mkdir -p /etc/rpm
  - sudo cp config/macros.cmake /etc/rpm

script:
  - bash check_dependencies.sh
  - bash build_model_rpm.sh -m hydrotrend
