language: python
python:
  - "2.7"

install: 
  - sudo apt-get install -qq rpm gfortran
  - bash .travis/install_packagebuilder.sh
  - bash .travis/install_rpmdevtools.sh
  - export PATH=$PATH:$PWD/rpmdevtools-6.8/

before_script:
  - sudo mkdir -p /etc/rpm
  - sudo cp config/macros.cmake /etc/rpm
  - which gfortran
  - export FC=$(which gfortran)

script:
   - build_rpm 2dflowvel --local $PWD/2dflowvel
